version: "3" # swarm mode compatible
services:
  web:
    # replace username/repo:tag with your name and image details
    image: silhouette88/get-started:part1
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
